
=head1 The Object System

=head2 Thoughts

I'm not going to try to implement the object system in pure Deck.
You're welcome.

For now, builtin types (list, string, etc.) are not OOPS.  That will
change.

Objects are a special type.

Classes are also a special type.  They are also callable and create
instances, then call 'INIT' with their arguments.

Let's use 'new' to create instances.  There's no real advantage to
making classes callable.

I'm not going to use the Perl object system until I have a better
grasp of everything.

=head2 Syntax

	class Foo (Object) {
		var xxx = 42
		var yyy = 53

		method INIT {x} {puts x}

		method bar {a} {puts a}
		method quux {b} {puts b}
	}


=head2 Semantics


=head2 To Do

	-basic class and object
		-'class' type.
		-'object' type.
X			-doesNotUnderstand
		-lookup function.
			-special syntax for lookup.
		-class definition
			-class macro
			-_::class function
				-inheritance
				-methods
					-private methods
				-instance variables
				-attributes
		-class 'Object'

		-object instantiation
		










