
=head1 The Object System

=head2 Thoughts

I'm not going to try to implement the object system in pure Deck.
You're welcome.

For now, builtin types (list, string, etc.) are not OOPS.  That will
change.

Objects are a special type.

Classes are also a special type.  They are also callable and create
instances, then call 'INIT' with their arguments.

Let's use 'new' to create instances.  There's no real advantage to
making classes callable.

I'm not going to use the Perl object system until I have a better
grasp of everything.

=head2 Syntax

	class Foo Object {
		var xxx = 42
		var yyy = 53

		method INIT {x} {puts x}

		method bar {a} {puts a}
		method quux {b} {puts b}
	}


	[o->m 42]

	-"->" is magical.
		-in prefix expressions, o->m is equivalent to (o->m) 
		 at the start of an expression
		-if escaped, behaves as usual.

	-"." is magical
			o.xxx = 123
			o.yyy = o.xxx + 42
			z = [foo o.xxx o.yyy]
		-'.' magically autoparens
X		-'.' needs higher precedence than '->'.
X			o.so->foo




=head2 Semantics

	-instance variables are visible only to the object's methods, NOT to
	 subclasses and NOT to methods added after the fact.

	-where is 'self' added?

		stdout->print 42

		[\-> stdout print] 42

		var n = stdout->print
		n 42

	-what if a local class existed in the context that defined it?

	-'attrib' declares 'public' ivars.

=head2 To Do

	-basic class and object
X		-'class' type.
			-equals
			-perlform
			-at, atPut, size, isIndexible
X		-'object' type.
X			-doesNotUnderstand
X		-lookup function.
			-special syntax for lookup.
		-class definition
			-class macro
X			-_::class function
				-inheritance
X				-methods
					-private methods
X					-must return self
					-self must be const
					-super
X				-instance variables
				-attributes
					-access methods
					-'.'
						-assignment support
						-autoparen
						-_set must return assignment value
			-initializer
X				-field initialization  (left out for now--spooky)
X		-class 'Object'
X			-isTrue

		-binary operator to method conversion

X		-object instantiation
	
		-make LL::Object a subclass of Context.
	




=head2 Issues

	-does a field decl. like "var x = [foo 4 2]" work?
		-what field order should I use?
		-how do I initialize them.
			-maybe define a bunch of unnamed methods to do it?










