
=head1 MProc Format



form: mproc <name> [
 [strict? [default <literal>]? (sub (\d+|(\w+)+)|sym|list|word) <arg>]*
] <body>
 
modifiers:
	sub number 	    -- If a list, subify's with number arguments.
                       Number is optional.
	sub [arg1..argn]-- If a list, subify's with named arguments.
	symbol			-- If a symbol, quote
	list			-- If a list, quote
    word            -- Must be the exact symbol as the arg. name.
	strict			-- Require that the other modifier activate.
	default         -- Provide a default value, making this argument optional.
                       Default value must be a number, string, quoted list,
                       symbol or nil.

so basically, mproc args must be LoLs.
 
  
    mproc map {
    	strict sub 1 block
    	items
    } {
    	var result = [listSized [block size]]
    	var index = 0
    
    	foreach item in items {
    		result@index = [block item]
    		index = index + 1
    	}
    
    	return result
    }



	mproc foo {
		strict sub op
		strict sub 0 getVal [default {value 42}] 
		symbol name [default :thingy]
	} {
		...
	}

=head2 default

To implement default:

	1) 